### PR TITLE
build on raspios-2021-10-30 with clang-11

### PR DESCRIPTION
**Pull request by sheffler**
clang-11 is default on raspios-2021-10-30 (bullseye), but libdispatch does not build properly.  The solution adopted here was to patch the flags passed to the compiler to ignore certain int-to-float warmings.

### CODE REVIEW

**Comment by plaurent** [comment]
Hi @sheffler I think I saw those same warnings and was able to get rid of them by moving to the current master branch of the libdispatch repo — could you check if master builds ok for this case?

**Comment by plaurent** [comment]
(as opposed to the 5.1.1 branch we have been pinning to)

**Comment by sheffler** [comment]
Doing a fresh clone and compiling on the master branch (origin/main) does not work.  Here is the error message.  Strange that it works on mobian-debian-12.

```
cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DUSE_GOLD_LINKER=YES
make

================================================================

[  8%] Building C object src/CMakeFiles/dispatch.dir/benchmark.c.o
/home/pi/libdispatch-testbuild/swift-corelibs-libdispatch/src/benchmark.c:63:10: error: implicit conversion from 'uint64_t' (aka 'unsigned long long') to 'long double' may lose precision [-Werror,-Wimplicit-int-float-conversion]
        lcost = delta;
              ~ ^~~~~
/home/pi/libdispatch-testbuild/swift-corelibs-libdispatch/src/benchmark.c:70:29: error: implicit conversion from 'unsigned long long' to 'long double' changes value from 18446744073709551615 to 18446744073709551616 [-Werror,-Wimplicit-const-int-float-conversion]
        bdata->loop_cost = lcost > UINT64_MAX ? UINT64_MAX : (uint64_t)lcost;
                                 ~ ^~~~~~~~~~
/usr/include/stdint.h:130:23: note: expanded from macro 'UINT64_MAX'
# define UINT64_MAX             (__UINT64_C(18446744073709551615))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/stdint.h:110:25: note: expanded from macro '__UINT64_C'
#  define __UINT64_C(c) c ## ULL
                        ^~~~~~~~
<scratch space>:56:1: note: expanded from here
18446744073709551615ULL
^~~~~~~~~~~~~~~~~~~~~~~
/home/pi/libdispatch-testbuild/swift-corelibs-libdispatch/src/benchmark.c:116:15: error: implicit conversion from 'uint64_t' (aka 'unsigned long long') to 'long double' may lose precision [-Werror,-Wimplicit-int-float-conversion]
        conversion = delta;
                   ~ ^~~~~
/home/pi/libdispatch-testbuild/swift-corelibs-libdispatch/src/benchmark.c:121:14: error: implicit conversion from 'uint64_t' (aka 'unsigned long long') to 'long double' may lose precision [-Werror,-Wimplicit-int-float-conversion]
        big_denom = delta;
                  ~ ^~~~~
/home/pi/libdispatch-testbuild/swift-corelibs-libdispatch/src/benchmark.c:125:20: error: implicit conversion from 'unsigned long long' to 'long double' changes value from 18446744073709551615 to 18446744073709551616 [-Werror,-Wimplicit-const-int-float-conversion]
        ns = conversion > UINT64_MAX ? UINT64_MAX : (uint64_t)conversion;
                        ~ ^~~~~~~~~~
/usr/include/stdint.h:130:23: note: expanded from macro 'UINT64_MAX'
# define UINT64_MAX             (__UINT64_C(18446744073709551615))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/stdint.h:110:25: note: expanded from macro '__UINT64_C'
#  define __UINT64_C(c) c ## ULL
                        ^~~~~~~~
<scratch space>:58:1: note: expanded from here
18446744073709551615ULL
^~~~~~~~~~~~~~~~~~~~~~~
5 errors generated.
make[2]: *** [src/CMakeFiles/dispatch.dir/build.make:108: src/CMakeFiles/dispatch.dir/benchmark.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1118: src/CMakeFiles/dispatch.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

**Comment by plaurent** [comment]
@sheffler Thank you for checking; very odd indeed.  Merging!

**Pull request merged**
