### PR TITLE
fix the build for Ubuntu24.04

### PR DESCRIPTION
**Pull request by sheffler**
Minor modification - see readme.txt for info

### CODE REVIEW

**Comment by plaurent** [comment]
@sheffler Fantastic. I noticed there are two shell scripts in this PR, one with a tilde at the end. Which file should we keep, do we need the `libc++-dev` to be installed?

```
~/gnustep-build/ubuntu-24.04-clang-18.0-runtime-2.1$ diff GNUstep-buildon-ubuntu2404.sh GNUstep-buildon-ubuntu2404.sh~
33c33
< g++-14
---
> libc++-dev g++-14
ubuntu@ip-172-31-47-3:~
```

**Comment by plaurent** [comment]
@sheffler Also I noticed I couldn't run `../demo-gui.sh` after installation -- wondering if we've lost something along the way (it cannot find AppKit.... so libs-gui might have an issue)

**Comment by sheffler** [comment]
You're right This is not running to completion.  The build of libs-corebase is failing, and that halts before libs-gui.  Will look into.

Also, the "~" file shouldn't be there.

**Comment by sheffler** [comment]
Fixed up args for libs-corebase.  Required adding more variables to the ./configure step.
Prepared for Docker testing and verified that it worked.
Changed Docker path to its forever home: github.com/plaurent

running
$ sudo ./test.sh

now worked successfully for me.

**Comment by plaurent** [comment]
@sheffler Thank you sir!  Will merge asap!

**Comment by sheffler** [comment]
Debian-12-clang-14.0 build.  tested against docker file.

**Pull request merged**
